/* Idea from https://github.com/tommoor/emojione-picker */
export default function createEmojisFromStrategy() {
  const emojis = {
    greek: {
      Alpha: "A",
      Beta: "B",
      Gamma: "\\Gamma",
      Delta: "\\Delta",
      Epsilon: "E",
      Zeta: "Z",
      Eta: "H",
      Theta: "\\Theta",
      Iota: "I",
      Kappa: "K",
      Lambda: "\\Lambda",
      Mu: "M",
      Nu: "N",
      Xi: "\\Xi",
      Omicron: "O",
      Pi: "\\Pi",
      Rho: "P",
      Sigma: "\\Sigma",
      Tau: "T",
      Upsilon: "\\Upsilon",
      Phi: "\\Phi",
      Chi: "X",
      Psi: "\\Psi",
      Omega: "\\Omega",

      alpha: "\\alpha",
      beta: "\\beta",
      gamma: "\\gamma",
      delta: "\\delta",
      epsilon: "\\epsilon",
      zeta: "\\zeta",
      eta: "\\eta",
      theta: "\\theta",
      iota: "\\iota",
      kappa: "\\kappa",
      lambda: "\\lambda",
      mu: "\\mu",
      nu: "\\nu",
      xi: "\\xi",
      omicron: "\\omicron",
      pi: "\\pi",
      rho: "\\rho",
      sigma: "\\sigma",
      tau: "\\tau",
      upsilon: "\\upsilon",
      phi: "\\phi",
      chi: "\\chi",
      psi: "\\psi",
      omega: "\\omega",
    }
  }
  return emojis;
}
