export default function createEmojisFromStrategy() {
  const emojis = {
    greek: {
      Alpha: { text: 'A' },
      Beta: { text: 'B' },
      Gamma: { text: 'Γ' },
      Delta: { text: 'Δ' },
      Epsilon: { text: 'E' },
      Zeta: { text: 'Z' },
      Eta: { text: 'H' },
      Theta: { text: 'Θ' },
      Iota: { text: 'I' },
      Kappa: { text: 'K' },
      Lambda: { text: 'Λ' },
      Mu: { text: 'M' },
      Nu: { text: 'N' },
      Xi: { text: 'Ξ' },
      Omicron: { text: 'O' },
      Pi: { text: 'Π' },
      Sigma: { text: 'Σ' },
      Tau: { text: 'T' },
      Upsilon: { text: 'Υ' },
      Phi: { text: 'Φ' },
      Chi: { text: 'X' },
      Psi: { text: 'Ψ' },
      Omega: { text: 'Ω' },
      Rho: { text: 'Ρ' },
      alpha: { text: 'α' },
      beta: { text: 'β' },
      gamma: { text: 'γ' },
      delta: { text: 'δ' },
      epsilon: { text: 'ε' },
      zeta: { text: 'ζ' },
      eta: { text: 'η' },
      theta: { text: 'θ' },
      iota: { text: 'ι' },
      kappa: { text: 'κ' },
      lambda: { text: 'λ' },
      mu: { text: 'μ' },
      nu: { text: 'ν' },
      xi: { text: 'ξ' },
      omicron: { text: 'ο' },
      pi: { text: 'π' },
      sigma: { text: 'σ' },
      tau: { text: 'τ' },
      upsilon: { text: 'υ' },
      phi: { text: 'φ' },
      chi: { text: 'χ' },
      psi: { text: 'ψ' },
      omega: { text: 'ω' },
      rho: { text: 'ρ' },
    },
    factor: {
      exa: { text: 'E' },
      peta: { text: 'P' },
      tera: { text: 'T' },
      giga: { text: 'G' },
      mega: { text: 'M' },
      kilo: { text: 'k' },
      deci: { text: 'd' },
      centi: { text: 'c' },
      milli: { text: 'm' },
      micro: { text: 'μ' },
      nano: { text: 'n' },
      pico: { text: 'p' },
      femto: { text: 'f' },
      atto: { text: 'a' },
      zepto: { text: 'z' },
      yocto: { text: 'y' },
    },
    constants: {
      planck: { text: 'h' },
      reducedPlanck: { text: 'ħ' },
      atomic: { text: 'amu' },
      boltzmann: { symbol: 'boltzmann', html: 'k<sub>B</sub>' },
      molar: { text: 'R' },
      avogadro: { symbol: 'avogadro', html: 'N<sub>A</sub>' },
      speedOfLight: { text: 'c' },
      mass: { symbol: 'mass', html: 'm<sub>e</sub>' },
      elementary: { text: 'e' },
      permittivity: { symbol: 'permittivity', html: 'ε<sub>0</sub>' },
      vacuum: { symbol: 'vacuum', html: 'μ<sub>0</sub>' },
    },
  };
  return emojis;
}
